### ISSUE TITLE
"Uncaught TypeError: e.path is undefined"

### ISSUE THREAD

**Issue by emresaracoglu** [TA3/web-user-behaviour#1]
Hello,

Thanks for the script, great job!
I get this error after clicking. How can I go about solving this?

`Uncaught TypeError: e.path is undefined`

[Code line](https://github.com/TA3/web-user-behaviour/blob/2ed0db586e96a31af29b96221d3b15465fda20a0/userBehaviour.js#L38)

Thank you

**Comment by laxris** [comment]
e.path only exists for Chrome. You should replace e.path by e.composedPath() in line 38 and 39 and it works again, for all browsers.
